version: '2'
services:
  jenkins:
    image: 'jenkins/jenkins'
    container_name: 'jenkins'
    labels:
      kompose.service.type: nodeport
    ports:
      - '8080:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - /svr/data/jenkins_data:/jenkins_home
      - /svr/data/jenkins:/var/jekins_config
volumes:
  jenkins_data:
    driver: local
  jenkins:
    driver: local

